server:
  port: 8082
spring:
  application:
    name: "study-service"
  datasource:
    url: jdbc:mysql://localhost:3306/studydb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9081/eureka/
    eureka-server-read-timeout-seconds: 100

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

openapi:
  service:
    title: study-service-doc
    version: 1.0.0
    url: http://localhost:9080 # api gateway host

springdoc:
  api-docs:
    path: /study-service/v3/api-docs
  swagger-ui:
    path: /study-service/swagger-ui.html